ALTER TABLE `Usuario`
ADD COLUMN `doisFatoresAtivo` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `doisFatoresCodigoHash` VARCHAR(191) NULL,
ADD COLUMN `doisFatoresExpiraEm` DATETIME(3) NULL,
ADD COLUMN `doisFatoresTentativas` INTEGER NOT NULL DEFAULT 0;
