ALTER TABLE "RiscoCatalogo" ADD COLUMN "ano" INTEGER NOT NULL DEFAULT 2026;
ALTER TABLE "RiscoCatalogo" ADD COLUMN "local" TEXT;
ALTER TABLE "RiscoCatalogo" ADD COLUMN "area" TEXT;
ALTER TABLE "RiscoCatalogo" ADD COLUMN "origemRisco" TEXT;
ALTER TABLE "RiscoCatalogo" ADD COLUMN "responsavelNome" TEXT;

ALTER TABLE "AnaliseRisco" ADD COLUMN "area" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "tituloRisco" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "origemRisco" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "causaProvavel" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "consequencia" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "pessoasAfetadas" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "controlesExistentes" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "probabilidadeValor" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "impactoValor" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "resultadoRisco" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "nivelAceitacao" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "tratamentoRisco" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "acaoProposta" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "custoEstimado" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "prioridade" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "statusAcao" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "observacoes" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "novaProbabilidade" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "novoImpacto" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "novoResultado" INTEGER;
ALTER TABLE "AnaliseRisco" ADD COLUMN "novoNivelRisco" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "observacaoReavaliacao" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "dataReavaliacao" DATETIME;
ALTER TABLE "AnaliseRisco" ADD COLUMN "responsavelReavaliacao" TEXT;
ALTER TABLE "AnaliseRisco" ADD COLUMN "anulado" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AnaliseRisco" ADD COLUMN "motivoAnulacao" TEXT;
