ALTER TABLE `ConfiguracaoSistema`
ADD COLUMN `smtpAtivo` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `smtpHost` VARCHAR(191) NULL,
ADD COLUMN `smtpPorta` INTEGER NOT NULL DEFAULT 587,
ADD COLUMN `smtpSeguro` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `smtpUsuario` VARCHAR(191) NULL,
ADD COLUMN `smtpSenha` VARCHAR(191) NULL,
ADD COLUMN `smtpRemetente` VARCHAR(191) NULL,
ADD COLUMN `smtpRespostaPara` VARCHAR(191) NULL;
