import { Router } from "express";
import { autenticarUsuario } from "../middlewares/auth";
import { excluirConta, excluirFornecedor, excluirRequisicao, listarContas, listarFornecedores, listarRequisicoes, resumoFinanceiro, salvarConta, salvarFornecedor, salvarRequisicao } from "../controllers/financeiro.controller";
const router = Router();
router.use(autenticarUsuario);
router.get("/fornecedores", listarFornecedores);
router.post("/fornecedores", salvarFornecedor);
router.put("/fornecedores/:id", salvarFornecedor);
router.delete("/fornecedores/:id", excluirFornecedor);
router.get("/contas", listarContas);
router.post("/contas", salvarConta);
router.put("/contas/:id", salvarConta);
router.delete("/contas/:id", excluirConta);
router.get("/resumo", resumoFinanceiro);
router.get("/requisicoes", listarRequisicoes);
router.post("/requisicoes", salvarRequisicao);
router.put("/requisicoes/:id", salvarRequisicao);
router.delete("/requisicoes/:id", excluirRequisicao);
export default router;
